/**
 * Shared TypeScript types for the Cloudflare MCP Workspace.
 *
 * Binding types come from `worker-configuration.d.ts` (generated by
 * `wrangler types` or maintained in-repo). Secrets are declared here
 * because they are not listed as wrangler vars.
 */

export interface Env extends Cloudflare.Env {
  GITHUB_CLIENT_ID?: string;
  GITHUB_CLIENT_SECRET?: string;
  COOKIE_ENCRYPTION_KEY?: string;
  HTML_DEPLOY_TOKEN?: string;
  EMAIL_API_URL?: string;
  EMAIL_API_KEY?: string;
  CF_ACCOUNT_ID?: string;
  CF_API_TOKEN?: string;
}

export interface AuthProps {
  userId: string;
  username?: string;
  displayName?: string;
  email?: string;
  avatarUrl?: string;
  provider?: "github" | "access" | "demo";
  scopes?: string[];
}

export interface NoteRow {
  id: string;
  title: string;
  content: string;
  tags: string;
  user_id: string | null;
  created_at: string;
  updated_at: string;
  embedding_id: string | null;
}

export interface DocumentRow {
  id: string;
  key: string;
  filename: string;
  mime_type: string;
  size_bytes: number;
  user_id: string | null;
  description: string | null;
  created_at: string;
  updated_at: string;
}

export interface EmailTemplateRow {
  id: string;
  name: string;
  subject: string;
  html: string;
  text: string | null;
  brand_name: string | null;
  variables: string;
  user_id: string | null;
  created_at: string;
  updated_at: string;
}

export interface EmailSendRow {
  id: string;
  to_addrs: string;
  subject: string;
  status: string;
  provider_message_id: string | null;
  template_id: string | null;
  tags: string;
  metadata: string | null;
  error: string | null;
  user_id: string | null;
  created_at: string;
  updated_at: string;
}

export interface IndexJob {
  kind: "note" | "document" | "delete";
  id: string;
  userId?: string | null;
  vectorIds?: string[];
  requestedAt: string;
}

export function textResult(text: string, isError = false) {
  return {
    content: [{ type: "text" as const, text }],
    isError,
  };
}

export function structuredResult<T>(data: T, text?: string, isError = false) {
  const payload = text ?? JSON.stringify(data, null, 2);
  return {
    content: [{ type: "text" as const, text: payload }],
    structuredContent: data,
    isError,
  };
}
