/**
 * Shared TypeScript types for the Cloudflare MCP Workspace.
 *
 * Binding types come from `worker-configuration.d.ts` (generated by
 * `wrangler types`). Secrets are declared here because they are not
 * listed in wrangler.jsonc.
 */

/** Secrets + any extra fields on top of the generated Cloudflare.Env */
export interface Env extends Cloudflare.Env {
  // Secrets (set via `wrangler secret put` — not present in wrangler.jsonc)
  GITHUB_CLIENT_ID?: string;
  GITHUB_CLIENT_SECRET?: string;
  COOKIE_ENCRYPTION_KEY?: string;
}

/** Auth props attached by workers-oauth-provider after successful login */
export interface AuthProps {
  userId: string;
  username?: string;
  displayName?: string;
  email?: string;
  avatarUrl?: string;
  provider?: "github" | "access" | "demo";
}

/** Standard note row */
export interface NoteRow {
  id: string;
  title: string;
  content: string;
  tags: string; // JSON
  user_id: string | null;
  created_at: string;
  updated_at: string;
  embedding_id: string | null;
}

/** Document metadata row */
export interface DocumentRow {
  id: string;
  key: string;
  filename: string;
  mime_type: string;
  size_bytes: number;
  user_id: string | null;
  description: string | null;
  created_at: string;
  updated_at: string;
}

/** Helper to produce consistent MCP text responses */
export function textResult(text: string, isError = false) {
  return {
    content: [{ type: "text" as const, text }],
    isError,
  };
}

/** Helper for structured + text results */
export function structuredResult<T>(data: T, text?: string) {
  const payload = text ?? JSON.stringify(data, null, 2);
  return {
    content: [{ type: "text" as const, text: payload }],
    structuredContent: data,
  };
}
